### ISSUE TITLE
No usas el destructuring

### ISSUE THREAD

**Issue by lmagarin** [javiloji/ReEntregaFormularioCompletito#3]
https://github.com/javiloji/ReEntregaFormularioCompletito/blob/66480d63fe78610c7cb34a5139fa32daa92465cb/js/validar.js#L114

**Comment by javiloji** [comment]
Si lo estoy usando en esta linea, ¿no?
            
let [, dniNumero, dniLetra] = expresiones.arrayDni[0].exec(dniCompleto);

**Comment by lmagarin** [comment]
POR FAVOR, lee tu propio código y analízalo.
